faiss_db:
  collection_name: "document_portal"

embedding_model:
  provider: "google"
  model: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model: "models/deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model: "models/text-embedding-004"
    temperature: 0
    max_output_tokens: 2048
